### ISSUE TITLE
why cannot get expected accuracy?

### ISSUE THREAD

**Issue by Lovegood-1** [bbartoldson/GeneralizationStabilityTradeoff#1]
Hi,

when I run
`python experiments.py -r F2_VGG_0 --arch vgg11_bn --adam --lr 0.001 --epochs 325 -d cifar100 
`
i cannot get the accuracy of baseline which is around 70%, actually I just get top1:56%.

Why?

**Comment by bbartoldson** [comment]
Hi,

I think the issue here is use of "cifar100" in your command. If you are trying to recreate the Figure 2 VGG experiments, then you should remove the extra "0" in your quoted command to ensure that you are using "cifar10" data. When I remove the extra "0" from the end of the command you listed, I get the expected 85% baseline accuracy (you should see 60+% test accuracy after just 1 training epoch). 

Since you expected 70% baseline accuracy, I think you may be trying to run the "cifar100" experiments shown in Table F.1. Those experiments train ResNet18 on "cifar100", so you will have to modify your command accordingly; for instance, you should change the "--arch" argument to "resnet18". The exact command to use for those experiments is [here](https://github.com/bbartoldson/GeneralizationStabilityTradeoff/blob/main/scripts_for_experiments/Table_F1.sh). When I run: 
`python experiments.py -r TF1_0 --arch resnet18 --adam --lr 0.0001 --epochs 4000 -d cifar100 --augment`, I get 62% top1 test accuracy by epoch 15.

Please let me know if that doesn't clear things up or if you have any other questions.

Thanks!

Brian
